[package]
name = "onchain_id_starknet"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.2"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.2"
openzeppelin_access = "0.20.0"
openzeppelin_introspection = "0.20.0"
openzeppelin_upgrades = "0.20.0"
openzeppelin_account = "0.20.0"

[dev-dependencies]
snforge_std = "0.35.1"

[[target.starknet-contract]]
sierra = true

[tool.fmt]
sort-module-level-items = true

[scripts]
test = "snforge test"
