[package]
name = "onchain_id_starknet"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.4"
scarb-version = "2.9.4"

[dependencies]
starknet = "2.9.4"
openzeppelin_access = "1.0.0"
openzeppelin_introspection = "1.0.0"
openzeppelin_upgrades = "1.0.0"
openzeppelin_account = "1.0.0"

[dev-dependencies]
snforge_std = "0.37.0"

[lib]
sierra = true
casm = false

[[target.starknet-contract]]
sierra = true
casm = false

[tool.fmt]
sort-module-level-items = true

[scripts]
test = "snforge test"