name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/setup-snfoundry@v4
      - uses: software-mansion/setup-scarb@v1.5.0
      - run: scarb fmt --check
      - run: snforge test
